

# Database Configuration
server:
  port: 6060

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/TRAIN_INFO
    username: root
    password: Ryzen@12
    driver-class-name : com.mysql.cj.jdbc.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 524334882640-smkp5fo233eps18o54g9842u3vtdqi0h.apps.googleusercontent.com
            clientSecret: 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





  main:
    web-application-type=none:
    allow-circular-references: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true







